### ISSUE TITLE
Ang: The calculator does not work at all.

### ISSUE THREAD

**Issue by lennartquerter** [lloydst/rekenmachine#15]
when pressing buttons i do not get the answers i expect

**Comment by lloydst** [comment]
correction* works untill the = key is pressed.
first function works allways.
a function like this: 2+3*8/2-1 also works but if = is pressed somewhere it stops working at that point.
working on a fix for the = now

**Comment by lloydst** [comment]
added a 2nd bar in which the previous answer has been stored since the equal key doesn't want to behave
